server:
  port: 8030
spring:
  application:
    name: cppc-ai-agent
  datasource:
    url: jdbc:postgresql://localhost:5432/cppc_platform
    username: cppcadmin
    password: cppcadmin
    driver-class-name: org.postgresql.Driver
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
